using BuilderBuilder.Compilers;
using Xunit;

namespace BuilderBuilder.Test.Compilers;

public class RecordCompilerTest
{
    private readonly RecordCompiler _sut = new();

    [Fact]
    public void ShouldGenerateRecord()
    {
        var entity = new BuilderEntity(false)
        {
            Name = "RecordTest",
            Fields =
            {
                new Field("Guid", "Id"),
                new Field("string", "Name")
            }
        };
        var result = _sut.Compile(entity);

        const string expected = @"// Autogenerated, manual changes could be overridden on regeneration
public record RecordTestBuilder
{
    public Guid Id { private get; init; }
    public string Name { private get; init; }

    public RecordTest Build() => new()
    {
        Id = Id,
        Name = Name,
    };
}
";
        Assert.Equal(expected, result);
    }
}